// Generated by scripts/generate-case-assets.mjs. Do not edit.
import type { SmartCityCase } from "./case-model";
export const caseAssets = [
  {
    "id": "luohu-cim-platform",
    "slug": "luohu-cim-platform",
    "title": "罗湖区时空信息赋能平台（CIM平台）项目",
    "province": "广东省",
    "city": "深圳市",
    "district": "罗湖区",
    "category": "规划建设",
    "year": 2024,
    "owner": "深圳市罗湖区相关建设管理部门",
    "locationLevel": "区县级",
    "lng": 114.1316,
    "lat": 22.5485,
    "locationConfidence": 0.9,
    "coverageType": "区县级场景",
    "status": "已发布",
    "sourceType": "招投标公告",
    "evidenceLevel": "中",
    "summary": "以统一时空信息底座和CIM平台支撑罗湖区规划建设、城市更新与空间治理业务，推动多源空间数据汇聚、共享和专题应用。",
    "painPoints": [],
    "solution": [],
    "outcomes": [],
    "aiTags": [
      "CIM",
      "时空信息",
      "城市更新",
      "空间治理",
      "BIM",
      "GIS"
    ],
    "expertView": "",
    "sourceNote": "由 knowledge-base/cases/luohu-cim-platform/case.md 生成。",
    "researchReport": "# 罗湖区时空信息赋能平台（CIM平台）项目\n\n## 项目概况\n\n项目面向罗湖区高密度建成区的规划建设和城市更新管理需求，建设统一的时空信息底座与CIM应用能力。平台以GIS空间数据为基础，融合建筑、项目和专题业务信息，为跨部门空间协同提供统一入口。\n\n## 建设背景\n\n罗湖区开发建设时间早、存量空间复杂，城市更新、重点片区建设和精细化治理对空间数据的完整性、现势性与协同使用提出了更高要求。原有数据分散在不同部门和系统，难以形成统一的空间表达和持续更新机制。\n\n## 核心问题\n\n- 多源空间数据标准和更新节奏不一致；\n- 项目、建筑与业务专题之间缺少统一空间关联；\n- 三维成果容易停留在展示层，尚需嵌入真实管理流程。\n\n## 建设内容\n\n平台围绕时空数据汇聚治理、二维三维一体化表达、BIM与GIS融合、专题应用和共享服务展开建设，并通过统一目录、接口和空间对象编码，为后续业务应用复用底座能力。\n\n## 应用价值\n\n项目的核心价值不是单独建设三维地图，而是以统一空间对象连接规划、建设、更新和治理信息，减少重复建库，并为跨部门研判与协同处置提供可追溯的空间依据。\n\n## 经验与启示\n\nCIM平台能否持续产生价值，取决于数据更新责任、业务调用频率和具体管理闭环。后续核验应继续补充正式建设范围、实施单位、业务使用成效和量化指标。",
    "asset": {
      "contentStatus": "published",
      "caseId": "luohu-cim-platform",
      "casePath": "knowledge-base/cases/luohu-cim-platform/case.md",
      "imageCount": 0,
      "sourceCount": 1,
      "poiStatus": "verified",
      "lastVerifiedAt": "2026-08-09"
    }
  }
] as SmartCityCase[];
