import type { SmartCityCase } from "./case-model";
import { migrateBuiltInCases } from "./benchmark-cases";

const legacySmartCityCases: SmartCityCase[] = [];

export const retiredDemoCases: SmartCityCase[] = [
  {
    id: "case-001",
    slug: "shenzhen-low-altitude-airspace-service",
    title: "深圳低空经济城市级空域服务与运行监管平台",
    province: "广东省",
    city: "深圳市",
    district: "南山区",
    category: "交通出行",
    year: 2024,
    owner: "市级主管部门 / 低空经济产业协同主体",
    locationLevel: "市级",
    lng: 114.0579,
    lat: 22.5431,
    locationConfidence: 0.82,
    coverageType: "城市级平台",
    status: "已发布",
    sourceType: "新闻报道",
    evidenceLevel: "中",
    summary:
      "围绕低空飞行申报、航线协同、运行监测和应急处置，构建城市级低空运行服务能力，为无人机物流、巡检、文旅和应急应用提供统一底座。",
    painPoints: ["低空应用多点试验但缺统一调度", "飞行活动与城市治理系统割裂", "安全监管与产业发展需要同步推进"],
    solution: ["空域资源数字化表达", "低空航线与任务协同管理", "飞行态势监测与事件联动"],
    outcomes: ["支撑多类低空应用试点", "提升飞行活动可视化监管能力", "形成低空经济城市治理样板"],
    aiTags: ["空域管理", "无人机物流", "城市运行", "监管平台"],
    expertView:
      "这类案例的关键不在单个无人机场景，而在城市能否形成可复用的低空运行规则、数据接口和安全闭环。",
    sourceNote: "演示数据：后续应绑定原始报道、政策或招标文件页码。",
  },
  {
    id: "case-002",
    slug: "shanghai-low-altitude-urban-logistics",
    title: "上海低空经济城市配送与综合监管示范",
    province: "上海市",
    city: "上海市",
    district: "浦东新区",
    category: "交通出行",
    year: 2024,
    owner: "新区管理机构 / 物流与低空运营企业",
    locationLevel: "区县级",
    lng: 121.5447,
    lat: 31.2215,
    locationConfidence: 0.78,
    coverageType: "区县级场景",
    status: "已发布",
    sourceType: "新闻报道",
    evidenceLevel: "中",
    summary:
      "以新区高密度商务与产业片区为场景，探索无人机配送、巡查与应急保障，并将低空运行数据纳入区域治理平台。",
    painPoints: ["超大城市末端配送效率压力", "高密度区域安全监管复杂", "低空应用缺少跨部门协同入口"],
    solution: ["重点片区航线试点", "运营企业接入统一监管", "与城市运行平台联动"],
    outcomes: ["形成片区级低空应用样板", "沉淀运营与监管协同经验", "推动产业场景从展示走向常态运营"],
    aiTags: ["低空配送", "浦东新区", "综合监管", "场景示范"],
    expertView:
      "上海样板更适合观察超大城市里的低空经济如何处理安全、效率和商业模式之间的平衡。",
    sourceNote: "演示数据：待替换为正式来源。",
  },
  {
    id: "case-003",
    slug: "hangzhou-city-brain-traffic",
    title: "杭州城市大脑交通治理应用",
    province: "浙江省",
    city: "杭州市",
    category: "交通出行",
    year: 2019,
    owner: "市级城市治理部门",
    locationLevel: "市级",
    lng: 120.1551,
    lat: 30.2741,
    locationConfidence: 0.88,
    coverageType: "城市级平台",
    status: "已发布",
    sourceType: "企业案例",
    evidenceLevel: "强",
    summary:
      "通过交通流量、信号控制、事件感知和指挥调度的协同，提升城市道路运行效率，是国内城市大脑类项目的重要参考。",
    painPoints: ["交通拥堵治理依赖人工经验", "跨部门数据难以实时协同", "突发交通事件响应链条长"],
    solution: ["交通数据实时汇聚", "信号配时优化", "事件发现与指挥调度联动"],
    outcomes: ["提升部分道路通行效率", "增强交通运行监测能力", "带动城市大脑概念扩展到多领域"],
    aiTags: ["城市大脑", "交通信号", "运行监测", "算法调度"],
    expertView:
      "适合作为‘平台型项目如何从单一场景切入’的基础案例，但复用时要警惕只复制大屏、不复制治理机制。",
    sourceNote: "演示数据：正式版本需补充指标来源与统计口径。",
  },
  {
    id: "case-004",
    slug: "guangzhou-cim-platform",
    title: "广州 CIM 基础平台与工程建设协同应用",
    province: "广东省",
    city: "广州市",
    category: "规划建设",
    year: 2022,
    owner: "住建与规划相关部门",
    locationLevel: "市级",
    lng: 113.2644,
    lat: 23.1291,
    locationConfidence: 0.84,
    coverageType: "城市级平台",
    status: "已发布",
    sourceType: "研究报告",
    evidenceLevel: "中",
    summary:
      "以三维城市空间底座支撑规划、建设、审批和城市更新等业务，推动 BIM、GIS、IoT 等数据在建设管理中的融合应用。",
    painPoints: ["工程建设数据分散在多系统", "二维审批难以支撑复杂空间判断", "城市更新需要更细粒度空间底座"],
    solution: ["CIM 三维空间底座", "BIM/GIS 融合", "建设项目全过程空间化管理"],
    outcomes: ["提升空间审查表达能力", "支撑工程建设协同管理", "为数字孪生城市应用提供底座"],
    aiTags: ["CIM", "BIM", "GIS", "工程建设"],
    expertView:
      "CIM 项目最容易变成数据展示工程，真正价值在于是否进入审批、建设、运维等高频业务流。",
    sourceNote: "演示数据：待补充平台建设边界和业务清单。",
  },
  {
    id: "case-005",
    slug: "beijing-urban-operation-command",
    title: "北京城市运行综合指挥与一网统管应用",
    province: "北京市",
    city: "北京市",
    category: "城市治理",
    year: 2023,
    owner: "市级城市运行管理机构",
    locationLevel: "市级",
    lng: 116.4074,
    lat: 39.9042,
    locationConfidence: 0.86,
    coverageType: "城市级平台",
    status: "已发布",
    sourceType: "政策文件",
    evidenceLevel: "中",
    summary:
      "围绕城市运行体征、网格事件、热线诉求、应急联动等内容，建设综合运行指挥体系，服务超大城市精细化治理。",
    painPoints: ["城市运行指标多但难以形成处置闭环", "热线、网格、应急之间协同成本高", "重大活动保障需要统一指挥"],
    solution: ["运行体征指标体系", "事件分拨闭环", "指挥调度一张图"],
    outcomes: ["提升跨部门协同效率", "增强重大活动保障能力", "沉淀城市运行指标框架"],
    aiTags: ["一网统管", "城市体征", "指挥调度", "热线联动"],
    expertView:
      "这类项目要重点看‘指标—事件—责任—反馈’是否闭环，否则大屏很漂亮但治理价值有限。",
    sourceNote: "演示数据：后续应补充制度文件和运行机制材料。",
  },
  {
    id: "case-006",
    slug: "chengdu-park-city-digital-governance",
    title: "成都公园城市智慧治理与生态价值转化应用",
    province: "四川省",
    city: "成都市",
    category: "生态低碳",
    year: 2023,
    owner: "城市治理与生态环境相关部门",
    locationLevel: "市级",
    lng: 104.0665,
    lat: 30.5723,
    locationConfidence: 0.8,
    coverageType: "城市级平台",
    status: "已发布",
    sourceType: "会议材料",
    evidenceLevel: "弱",
    summary:
      "围绕公园城市建设，将生态空间、绿道、碳汇、环境监测和市民服务进行数字化管理，探索生态价值可视化表达。",
    painPoints: ["生态资产难以量化管理", "公园城市建设涉及多部门协同", "公众服务与生态治理数据割裂"],
    solution: ["生态空间一张图", "绿道与公园服务数据接入", "生态价值指标化表达"],
    outcomes: ["增强生态治理可视化能力", "支撑公园城市品牌表达", "推动生态数据服务公众"],
    aiTags: ["公园城市", "生态资产", "绿道", "碳汇"],
    expertView:
      "该类案例有很强的城市品牌属性，分析时要把‘治理实效’和‘形象展示’分开看。",
    sourceNote: "演示数据：证据等级较弱，正式入库前需人工复核。",
  },
  {
    id: "case-007",
    slug: "suzhou-industrial-park-digital-twin",
    title: "苏州工业园区数字孪生园区运营平台",
    province: "江苏省",
    city: "苏州市",
    district: "苏州工业园区",
    category: "工业园区",
    year: 2022,
    owner: "园区管理机构",
    locationLevel: "园区/项目点",
    lng: 120.7069,
    lat: 31.3005,
    locationConfidence: 0.9,
    coverageType: "园区示范",
    status: "已发布",
    sourceType: "企业案例",
    evidenceLevel: "中",
    summary:
      "以园区空间、企业、能耗、交通、安防和招商服务为核心，构建园区级数字孪生运营管理能力。",
    painPoints: ["园区企业与空间数据分散", "招商、运营、安防各自为政", "园区管理需要更高频的运营指标"],
    solution: ["园区数字底座", "企业画像与空间资产管理", "运营指标驾驶舱"],
    outcomes: ["提升园区运营精细化水平", "支撑招商与企业服务", "增强园区安全与能耗管理"],
    aiTags: ["数字孪生园区", "企业画像", "招商运营", "空间资产"],
    expertView:
      "园区比城市更容易做出闭环，因为边界清楚、主体集中，适合作为商业化落地的优先方向。",
    sourceNote: "演示数据：待绑定园区公开资料。",
  },
  {
    id: "case-008",
    slug: "wuhan-emergency-flood-command",
    title: "武汉城市防汛应急指挥数字化应用",
    province: "湖北省",
    city: "武汉市",
    category: "市政韧性",
    year: 2021,
    owner: "应急、水务、城管等部门",
    locationLevel: "市级",
    lng: 114.3054,
    lat: 30.5928,
    locationConfidence: 0.79,
    coverageType: "城市级平台",
    status: "已发布",
    sourceType: "新闻报道",
    evidenceLevel: "中",
    summary:
      "接入雨情、水情、易涝点、泵站、排水管网和应急资源，实现城市内涝风险研判与防汛指挥调度。",
    painPoints: ["极端天气下城市内涝风险上升", "感知数据与应急资源分散", "现场处置需要快速联动"],
    solution: ["雨水情实时监测", "易涝点风险预警", "应急队伍与物资调度"],
    outcomes: ["提升防汛指挥效率", "增强风险点位感知能力", "支撑应急处置复盘"],
    aiTags: ["防汛", "内涝", "应急指挥", "水务"],
    expertView:
      "防汛类项目适合沉淀为可迁移方法论：风险对象、感知指标、阈值预警、处置资源四件事必须齐。",
    sourceNote: "演示数据：后续补充具体系统和指标口径。",
  },
  {
    id: "case-009",
    slug: "xiongan-city-digital-twin",
    title: "雄安新区数字孪生城市建设与规划管控",
    province: "河北省",
    city: "雄安新区",
    category: "规划建设",
    year: 2023,
    owner: "新区建设管理机构",
    locationLevel: "市级",
    lng: 115.861,
    lat: 39.043,
    locationConfidence: 0.83,
    coverageType: "城市级平台",
    status: "已发布",
    sourceType: "研究报告",
    evidenceLevel: "中",
    summary:
      "围绕新区规划建设全过程，构建数字孪生城市底座，服务规划管控、建设管理、基础设施运维与城市治理。",
    painPoints: ["新区建设需要从规划阶段即形成数字底座", "建设项目多、周期长、协同复杂", "城市运行能力需与实体建设同步形成"],
    solution: ["规划建设一体化数据底座", "BIM/CIM 融合管理", "基础设施数字化运维"],
    outcomes: ["支撑新区高标准规划建设", "推动数字城市与实体城市同步建设", "形成数字孪生城市标杆叙事"],
    aiTags: ["雄安", "数字孪生城市", "CIM", "规划管控"],
    expertView:
      "雄安案例的价值在于‘从新城建设初期同步数字化’，与存量城市改造逻辑不同。",
    sourceNote: "演示数据：正式版本需拆分规划、建设、运维多个子案例。",
  },
  {
    id: "case-010",
    slug: "ningbo-smart-port-city-transport",
    title: "宁波港城联动智慧交通与物流协同",
    province: "浙江省",
    city: "宁波市",
    category: "交通出行",
    year: 2022,
    owner: "交通与港口相关单位",
    locationLevel: "市级",
    lng: 121.5503,
    lat: 29.8746,
    locationConfidence: 0.77,
    coverageType: "城市级平台",
    status: "已发布",
    sourceType: "企业案例",
    evidenceLevel: "中",
    summary:
      "面向港口集疏运、货车通行、道路拥堵与物流效率问题，推动港口、交通和城市运行数据协同。",
    painPoints: ["港口物流对城市道路造成周期性压力", "货车调度与城市交通管理割裂", "物流效率与城市拥堵之间存在矛盾"],
    solution: ["港城交通数据融合", "货车通行引导", "物流节点运行监测"],
    outcomes: ["改善港区周边交通组织", "提升物流调度透明度", "为港城协同治理提供数据基础"],
    aiTags: ["港城联动", "智慧物流", "货车治理", "交通组织"],
    expertView:
      "港口城市的智慧交通不能只看路口效率，必须把产业物流链条纳入城市治理视角。",
    sourceNote: "演示数据：后续补充港口和交通部门资料。",
  },
  {
    id: "case-011",
    slug: "qingdao-city-cloud-governance",
    title: "青岛城市云脑与城市治理综合应用",
    province: "山东省",
    city: "青岛市",
    category: "城市治理",
    year: 2022,
    owner: "市级大数据与城市治理部门",
    locationLevel: "市级",
    lng: 120.3826,
    lat: 36.0671,
    locationConfidence: 0.76,
    coverageType: "城市级平台",
    status: "已发布",
    sourceType: "新闻报道",
    evidenceLevel: "中",
    summary:
      "整合城市运行、政务服务、基层治理和公共安全相关数据，形成面向治理决策和事件处置的城市智能中枢。",
    painPoints: ["数据资源归集后应用转化不足", "城市治理事件跨部门处置慢", "基层治理缺少上下一体协同"],
    solution: ["城市云脑数据中枢", "治理事件闭环流转", "重点指标态势分析"],
    outcomes: ["提升城市运行感知能力", "支撑治理事项协同处置", "强化数据资源场景化使用"],
    aiTags: ["城市云脑", "数据中枢", "基层治理", "事件闭环"],
    expertView:
      "云脑类案例要重点拆解数据、算法、业务流程三者关系，不能只把它当成数据平台。",
    sourceNote: "演示数据：待补充平台能力清单。",
  },
  {
    id: "case-012",
    slug: "nanjing-one-network-management",
    title: "南京城市治理一网统管区市联动应用",
    province: "江苏省",
    city: "南京市",
    category: "城市治理",
    year: 2023,
    owner: "市区两级城市治理机构",
    locationLevel: "市级",
    lng: 118.7969,
    lat: 32.0603,
    locationConfidence: 0.78,
    coverageType: "城市级平台",
    status: "待复核",
    sourceType: "政策文件",
    evidenceLevel: "弱",
    summary:
      "围绕市区联动、网格事件、城市部件和重点区域治理，建设城市治理一网统管能力。",
    painPoints: ["市区两级治理事项流转链条长", "城市部件和网格事件管理分散", "重点区域治理缺少统一视图"],
    solution: ["市区两级指挥协同", "网格事件归集", "重点区域专题治理"],
    outcomes: ["增强跨层级协同", "提高事件管理透明度", "为重点区域治理提供专题支撑"],
    aiTags: ["一网统管", "网格治理", "市区联动"],
    expertView:
      "该案例目前适合作为待复核样本，重点补证据：是否已有运行指标、是否形成制度化闭环。",
    sourceNote: "演示数据：后台显示为待复核，模拟 AI 已解析但未发布。",
  },
  {
    id: "case-013",
    slug: "hefei-government-service-ai",
    title: "合肥政务服务智能问答与办事导办应用",
    province: "安徽省",
    city: "合肥市",
    category: "数字政府",
    year: 2024,
    owner: "政务服务与数据管理部门",
    locationLevel: "市级",
    lng: 117.2272,
    lat: 31.8206,
    locationConfidence: 0.73,
    coverageType: "城市级平台",
    status: "已发布",
    sourceType: "新闻报道",
    evidenceLevel: "弱",
    summary:
      "利用知识库和智能问答能力，提升企业群众办事咨询、材料准备、事项导办和政策查询效率。",
    painPoints: ["办事事项多、政策口径复杂", "人工咨询压力大", "企业群众难以快速理解材料要求"],
    solution: ["政务知识库结构化", "智能问答导办", "事项材料清单生成"],
    outcomes: ["改善咨询体验", "降低窗口重复咨询", "推动政务知识资产沉淀"],
    aiTags: ["政务大模型", "智能问答", "办事导办", "知识库"],
    expertView:
      "政务 AI 项目必须把幻觉控制、来源引用和人工兜底设计放在首位。",
    sourceNote: "演示数据：需补充实际上线范围。",
  },
  {
    id: "case-014",
    slug: "fuzhou-water-environment-platform",
    title: "福州水环境智慧监管与河湖治理应用",
    province: "福建省",
    city: "福州市",
    category: "生态低碳",
    year: 2021,
    owner: "生态环境、水利与城管相关部门",
    locationLevel: "市级",
    lng: 119.2965,
    lat: 26.0745,
    locationConfidence: 0.75,
    coverageType: "城市级平台",
    status: "已发布",
    sourceType: "新闻报道",
    evidenceLevel: "中",
    summary:
      "围绕河湖水质、排口、巡河、问题整改和公众监督，建设水环境智慧监管应用。",
    painPoints: ["河湖问题发现滞后", "排口与污染源管理链条复杂", "巡河整改闭环难以追踪"],
    solution: ["水质监测接入", "排口与问题点位管理", "巡河整改闭环"],
    outcomes: ["提升水环境问题发现效率", "增强整改过程可追踪性", "支持河湖长制数字化"],
    aiTags: ["水环境", "河湖长制", "排口监管", "生态治理"],
    expertView:
      "环保类案例价值评估要特别关注监测数据是否进入执法、整改和绩效考核。",
    sourceNote: "演示数据：待补充监测指标。",
  },
  {
    id: "case-015",
    slug: "chongqing-mountain-city-cim",
    title: "重庆山地城市 CIM 与地下空间治理应用",
    province: "重庆市",
    city: "重庆市",
    category: "规划建设",
    year: 2023,
    owner: "规划自然资源与住建相关部门",
    locationLevel: "市级",
    lng: 106.5516,
    lat: 29.563,
    locationConfidence: 0.8,
    coverageType: "城市级平台",
    status: "已发布",
    sourceType: "会议材料",
    evidenceLevel: "弱",
    summary:
      "面向山地城市复杂地形、桥隧、轨道和地下空间管理需求，探索三维城市空间底座与专项治理应用。",
    painPoints: ["山地城市空间关系复杂", "地下空间、桥隧与地上建设协同难", "传统二维管理表达不足"],
    solution: ["三维地形与建筑融合", "地下空间专题管理", "工程项目空间校核"],
    outcomes: ["提升复杂空间表达能力", "支撑地下空间治理", "强化工程建设空间协同"],
    aiTags: ["山地城市", "CIM", "地下空间", "桥隧"],
    expertView:
      "重庆非常适合做 CIM 价值案例，因为空间复杂性本身就会放大三维底座的必要性。",
    sourceNote: "演示数据：需要补充公开项目边界。",
  },
  {
    id: "case-016",
    slug: "zhengzhou-emergency-command",
    title: "郑州极端天气应急指挥与城市生命线监测",
    province: "河南省",
    city: "郑州市",
    category: "市政韧性",
    year: 2023,
    owner: "应急管理与城市生命线相关部门",
    locationLevel: "市级",
    lng: 113.6254,
    lat: 34.7466,
    locationConfidence: 0.78,
    coverageType: "城市级平台",
    status: "已发布",
    sourceType: "政策文件",
    evidenceLevel: "中",
    summary:
      "围绕极端天气、城市内涝、桥隧、燃气、供水等城市生命线风险，建设监测预警与应急指挥应用。",
    painPoints: ["极端天气事件暴露城市生命线脆弱性", "风险监测与处置资源割裂", "预警信息需要更快触达责任主体"],
    solution: ["生命线感知监测", "风险预警模型", "应急指挥调度"],
    outcomes: ["提升风险感知能力", "增强应急响应协同", "推动生命线工程数字化"],
    aiTags: ["城市生命线", "极端天气", "风险预警", "应急指挥"],
    expertView:
      "生命线工程不是单纯装传感器，核心是风险分级、责任体系和应急处置流程。",
    sourceNote: "演示数据：待补充专项工程资料。",
  },
  {
    id: "case-017",
    slug: "xiamen-smart-parking-traffic",
    title: "厦门智慧停车与交通诱导一体化应用",
    province: "福建省",
    city: "厦门市",
    category: "交通出行",
    year: 2021,
    owner: "交通管理与停车运营主体",
    locationLevel: "市级",
    lng: 118.0894,
    lat: 24.4798,
    locationConfidence: 0.76,
    coverageType: "城市级平台",
    status: "已发布",
    sourceType: "企业案例",
    evidenceLevel: "中",
    summary:
      "整合路内外停车资源、诱导屏、移动端服务和交通管理数据，缓解停车难与局部拥堵问题。",
    painPoints: ["停车资源信息不透明", "找车位造成绕行拥堵", "停车运营与交通管理协同不足"],
    solution: ["停车资源联网", "余位诱导与预约服务", "交通诱导协同"],
    outcomes: ["提升停车资源利用率", "改善用户找车位体验", "为交通精细化管理提供数据"],
    aiTags: ["智慧停车", "交通诱导", "城市服务"],
    expertView:
      "停车项目商业闭环相对清晰，适合从运营收入、用户体验和治理效果三方面评估。",
    sourceNote: "演示数据：后续补充运营指标。",
  },
  {
    id: "case-018",
    slug: "changsha-industrial-internet-park",
    title: "长沙产业园区工业互联网与能耗管理应用",
    province: "湖南省",
    city: "长沙市",
    category: "工业园区",
    year: 2023,
    owner: "园区管委会 / 工业互联网服务商",
    locationLevel: "园区/项目点",
    lng: 112.9388,
    lat: 28.2282,
    locationConfidence: 0.7,
    coverageType: "园区示范",
    status: "草稿",
    sourceType: "招投标公告",
    evidenceLevel: "弱",
    summary:
      "面向园区企业能耗、设备运行、产线协同和安全生产需求，建设工业互联网与园区运营融合平台。",
    painPoints: ["企业能耗和设备数据难以统一接入", "园区管理缺少企业运行画像", "安全生产预警依赖人工巡查"],
    solution: ["企业数据接入", "能耗监测分析", "安全生产风险预警"],
    outcomes: ["形成园区企业运行画像", "辅助节能降耗管理", "支撑安全生产监管"],
    aiTags: ["工业互联网", "能耗管理", "园区运营"],
    expertView:
      "该样本仍是草稿，适合后续演示从招投标公告提取结构化字段的流程。",
    sourceNote: "演示数据：后台草稿，不进入公开统计。",
  },
  {
    id: "case-019",
    slug: "haikou-tourism-city-service",
    title: "海口文旅城市服务与游客体验数字化应用",
    province: "海南省",
    city: "海口市",
    category: "数字政府",
    year: 2024,
    owner: "文旅与政务服务相关部门",
    locationLevel: "市级",
    lng: 110.1983,
    lat: 20.0458,
    locationConfidence: 0.72,
    coverageType: "城市级平台",
    status: "已发布",
    sourceType: "新闻报道",
    evidenceLevel: "弱",
    summary:
      "围绕游客咨询、景区服务、消费引导和投诉处理，构建面向文旅城市的数字化服务入口。",
    painPoints: ["游客服务信息分散", "文旅消费与城市服务割裂", "投诉与应急事件需要及时响应"],
    solution: ["文旅服务聚合入口", "游客画像与消费引导", "投诉事件闭环处理"],
    outcomes: ["改善游客服务体验", "支撑文旅消费转化", "增强旅游旺季治理能力"],
    aiTags: ["智慧文旅", "游客服务", "城市服务"],
    expertView:
      "文旅数字化项目要同时看公共服务和消费转化，不能只做城市宣传入口。",
    sourceNote: "演示数据：待补充景区和平台资料。",
  },
  {
    id: "case-020",
    slug: "jinan-spatiotemporal-data-platform",
    title: "济南时空大数据平台与城市治理专题应用",
    province: "山东省",
    city: "济南市",
    category: "规划建设",
    year: 2022,
    owner: "自然资源与大数据相关部门",
    locationLevel: "市级",
    lng: 117.1201,
    lat: 36.6512,
    locationConfidence: 0.77,
    coverageType: "城市级平台",
    status: "已发布",
    sourceType: "研究报告",
    evidenceLevel: "中",
    summary:
      "以时空大数据平台为基础，支撑城市规划、自然资源监管、城市治理和公共服务等专题应用。",
    painPoints: ["空间数据分散且标准不一", "业务专题缺少统一时空底座", "数据共享和复用效率低"],
    solution: ["时空数据汇聚治理", "专题应用服务接口", "空间分析能力开放"],
    outcomes: ["提升空间数据复用效率", "支撑多部门专题应用", "为城市数字孪生奠定基础"],
    aiTags: ["时空大数据", "空间治理", "数据底座", "专题应用"],
    expertView:
      "时空平台是底座类项目，评估重点是被多少真实业务系统调用，而不是平台本身功能多少。",
    sourceNote: "演示数据：后续补充调用场景清单。",
  },
];

export const retiredSmartCityCases = migrateBuiltInCases(retiredDemoCases);

export const smartCityCases = migrateBuiltInCases(legacySmartCityCases);

export function getPublishedCases() {
  return smartCityCases.filter((item) => item.status === "已发布");
}

export function getCaseBySlug(slug: string) {
  return smartCityCases.find((item) => item.slug === slug);
}
